version: '3.8'

services:
  streamlit:
    build: ./streamlit_app  # Build context points to streamlit_app directory
    container_name: streamlit_app
    ports:
      - "8501:8501"
    restart: always